import Head from "next/head";
import { Inter } from "next/font/google";
import { GetServerSideProps, NextPage } from "next";
import { fetchArticles, fetchCategories } from "@/http";
import axios, { AxiosResponse } from "axios";
import { IArticle, ICategory, ICollectionResponse } from "@/types";
import Tabs from "@/components/Tabs";
import ArticleList from "@/components/ArticleList";

const inter = Inter({ subsets: ["latin"] });

interface IPropTypes {
  categories: {
    items: ICategory[];
  };
  articles: { items: IArticle };
}

const Home: NextPage<IPropTypes> = ({ categories, articles }) => {
  return (
    <>
      <Head>
        <title>{"Coder's Blog Homepage"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Tabs categories={categories.items} />

      {/* Articles */}
      <ArticleList articles={articles.items} />
    </>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async () => {
  // Fetch() Categories
  const { data: categories }: AxiosResponse<ICollectionResponse<ICategory[]>> =
    await fetchCategories();

  // Fetch() Articles
  const { data: articles }: AxiosResponse<ICollectionResponse<IArticle[]>> =
    await fetchArticles();

  return {
    props: {
      categories: {
        items: categories.data,
      },
      articles: {
        items: articles.data,
        pagination: articles.meta.pagination,
      },
    },
  };
};
